title: Stuff Here
description:
theme: minima
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Optional: Custom navigation
header_pages:
  - index.md
  - about.md
  - contact.md
